### ISSUE TITLE
Перевірте відповідність бібліотеки home-assistant-integration в архіві 

### ISSUE THREAD

**Issue by Kadagor** [v00g100skr/ukraine_alarm_map#159]
Скоріше всього бібліотека home-assistant-integration з архіву не відповідає інстальованій, з якою ви робили компіляцію. Наприклад HAMqtt.h з архіву не містить ConnectionState, але наведений параметр enum є в файлі https://github.com/dawidchyrzynski/arduino-home-assistant/blob/main/src/HAMqtt.h. Проте, якщо для компіляції використовувавти останню версію бібліотеки по наведеному мною посиланні виникнуть помилки з використанням класу HASensorNumber.h

**Comment by Foroxon** [comment]
Всі версії сторонніх бібліотек, що використовуються для збірки прошивки, можна знайти тут: https://github.com/v00g100skr/ukraine_alarm_map/blob/7eb845b50fa6b1a468c55c40d0e5b9cda77f1da0/.github/workflows/firmware-compile/action.yml#L34
Так, в архіві бібліотеки давно не оновлювались, швидше за все ми скоро приберемо їх звідти взагалі, а залишимо лише список бібліотек з версіями у Wiki.
Відносно помилки HASensorNumber, можливо ви використовуєте "агресивну" обробку попереджень при компіляції.
Виставте значення "По замовчуванню" в Arduino IDE (скріншот нижче), або використовуйте прапорець **--warnings=default** якщо користуєтесь командним рядком для збірки.

**Comment by Foroxon** [comment]
Хоч тікет і закритий вже, але відпишусь, що ми додали сторінку з описом залежностей у нашу [Wiki](https://github.com/v00g100skr/ukraine_alarm_map/wiki/%D0%A1%D1%82%D0%BE%D1%80%D0%BE%D0%BD%D0%BD%D1%96-%D0%B1%D1%96%D0%B1%D0%BB%D1%96%D0%BE%D1%82%D0%B5%D0%BA%D0%B8)
