### ISSUE TITLE
Доробки інтерфейсу

### ISSUE THREAD

**Issue by v00g100skr** [v00g100skr/ukraine_alarm_map#162]
~~1. помилка тексту на корегуванні тиску~~
~~2. в вкладці звуку зробити кнопку тестування бузера - щоб видавав або якийсь звук, або мелодію~~
~~3. показати актуальні значення сенсорів (температура, вологість, тиск, освітлення)~~
~~4. показати актуальне значення яскравості ледів~~
~~5. показати наявності сенсорів і дисплея (думаю можна в секціі де ip адреса)~~
~~6. показати десь технічну інфу, яку ми передаєм в ХА (память, температура проца і тп)~~
~~7. думаю, що яскравість дисплея можна обмежити двома значеннями - нормальне і притушене (чекбокс або селектбокс)~~
~~8. додати в ХА binary sensor наявності тривоги в домашньому дістрікті~~
~~9. додати в ХА значення з сенсорів~~

**Comment by v00g100skr** [comment]
10. коли нема дисплея - не працює слайдер кольору режима лампи

**Comment by Foroxon** [comment]
1, 5, 7, 10 пофіксив в beta 27

**Comment by Foroxon** [comment]
2 - done
https://github.com/v00g100skr/ukraine_alarm_map/pull/163

**Comment by Foroxon** [comment]
Все інше в https://github.com/v00g100skr/ukraine_alarm_map/pull/165
