### ISSUE TITLE
Повернути буззер в версію 3

### ISSUE THREAD

**Issue by v00g100skr** [v00g100skr/ukraine_alarm_map#51]
1. гімн на старті
2. сигнал початку тривоги
3. сигнал закінчення тривоги
4. сигнал кожну годину (зуммер на годинник)

всі сигнали повинні мати можливість повного вимкнення
всі сигнали повинні мати можливість вимкнення в нічному режимі або коли датчик світла реєструє темряву

**Comment by v00g100skr** [comment]
1. гімн на старті
2. сигнал початку тривоги
3. сигнал закінчення тривоги
4. сигнал кожну годину (зуммер на годинниик)

всі сигнали повинні мати можливість повного вимкнення
всі сигнали повиння мати можливисть вимкнення в нічному режимі або коли датчік світла рееструет темряву

**Comment by Foroxon** [comment]
Done
