### ISSUE TITLE
soft-button для HA - перемикання режимів

### ISSUE THREAD

**Issue by v00g100skr** [v00g100skr/ukraine_alarm_map#95]
тріггери (окремі) в HA для каруселі режимів екрана і мапи
використання - додати можливість керувати мапою (перемикати режими по аналогіі з фізичной кнопкой) через HA за допомогою зовнішніх пультів

**Comment by vheneraliuk** [comment]
А чи є в цьому сенс? можна ж просто перемикати через вже наявні сенсори вибору режимів.

**Comment by v00g100skr** [comment]
прикол саме в тому щоб повісити на простий клікер без логікі
звичайно ж можна перемикати на конкретний режим і назад автоматизацією з умовами

**Comment by Foroxon** [comment]
Взяв в роботу

**Comment by Foroxon** [comment]
Done
